#!/bin/bash
set -Eeuo pipefail

COZE_WORKSPACE_PATH="${COZE_WORKSPACE_PATH:-$(pwd)}"
MCP_SERVER_PORT="${MCP_SERVER_PORT:-5001}"
MCP_SERVER_HOST="${MCP_SERVER_HOST:-0.0.0.0}"

cd "${COZE_WORKSPACE_PATH}"

echo "Starting MCP Server on ${MCP_SERVER_HOST}:${MCP_SERVER_PORT}..."
MCP_SERVER_PORT=${MCP_SERVER_PORT} MCP_SERVER_HOST=${MCP_SERVER_HOST} node dist/mcp/server.js
